
["Configs for Modern Train Parts"]
	#If wires should render offscreen (might worsen performance)
	render_wires_offscreen = false
	#The spacing between wire hangers
	#Range: > 1
	wire_hanger_spacing = 2

